### ISSUE TITLE
Språk-krock

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#15]
På sidan _upload.php_, vid lyckad uppladdning av bild, presenteras information **på både** svenska och engelska.

- [ ] Ändra texten från engelska till svenska.
- [ ] Ge informationen på båda språken.
- [ ] Ge funktionaliteten att ha ett användar-valt språk (Session-variabler eller Språk-preferens i Databasen)

**Comment by Hugsim** [comment]
Inte ett problem - vi är international in our development
