### ISSUE TITLE
Visuella buggar

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#16]
Problem uppstår på _home.php,_ vid användning av Internet Explorer, är bilderna som visas alldeles för stora och hindrar användaren helt från att navigera på sidan. Vid ut-zoomning (10%) visas bilderna i rätt storlek men resten av gränssnittet är osynligt.

- [ ] Stöd för Internet Explorer-användare.

**Comment by Hugsim** [comment]
Använd en bättre webbläsare
