### ISSUE TITLE
Anmärkningsvärd formulärsbug

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#17]
På sidan _auth_SVAR.php_, vid uppladdning av bildfil, är **ingen** av radioknapparna förbockade. På sidan _upload.php_ visas ett **error-meddelande** för just detta.

- [x] En av radioknapparna förbockade.
- [x] Verifiering vid skickande av formulärsdatan.

**Comment by Hugsim** [comment]
Fixat genom 381d0c6390824b5842a8b59c73cbab2c174c6789
