### ISSUE TITLE
Bilduppladdningsformulärsproblem

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#18]
#17 Referens till tidigare påpekad bugg i formuläret. På sidan auth_SVAR.php, vid uppladdning av bildfil krävs varken Titel eller Beskrivning.

- [x] Required på åtminstone Titeln.

**Comment by Hugsim** [comment]
Fixat genom 74f9f6fd5af9cb9240fa9233602240f68d4aa211
