### ISSUE TITLE
Krävs Ingen Bild För Uppladdning Av Bild?

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#19]
#18 Referens till tidigare påträffat problem. Vid uppladdning av bildfil på sidan _auth_SVAR.php_, krävs inte en bildfil. Sidan man skickas vidare till, _upload.php_, säger att bilden är för stor.

- [x] Required på bildfils-input.

**Comment by Hugsim** [comment]
Redan fixat
