### ISSUE TITLE
Förbättrad och användarvänlig användarmiljö

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#21]
Ge användarna knappar att navigera på sidorna:
**_signup.php_**
- [x] Ge möjligheten att navigera **direkt** till inloggningsformuläret om användaren redan är har ett konto/medlemskap.
T.ex.
- [x] Ge möjligheten att navigera **direkt** till registreringsformuläret om användaren inte har ett konto/medlemskap.
T.ex.
- I form av en knapp "Logga in!".
- I form av en länk under formuläret: "Redan medlem? Logga in här".

_**login.html**_
- I form av en knapp "Registrera dig!".
- I form av en länk under formuläret: "Inte medlem? Registrera dig här".

**Comment by Hugsim** [comment]
Fixat genom dba1a094cb0b536db9e2ea0b012f26d68e4851ce
