### ISSUE TITLE
Loginformulär - ingen required!

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#22]
Filen **_login.html_** har ingen required på varken användarnamnet eller lösenordet.
Rad 16 och 22:
`<input class="input" type="text" name="user" required>`
[...]
`<input class="input" type="password" name="pass" required>`
- [x] Förbättra formuläret med required - på både användarnamnet och lösenordet.

**Comment by Hugsim** [comment]
Fixat genom fbb5b567b8eddce980057e09405c3bce439a73e5
