### ISSUE TITLE
Förbättring av kod vid kontroll av inloggningsuppgifter

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#23]
I filen _**auth_SVAR.php**_, Rad 32 f., varför inte som följande?
Rad 32:
`$sql = "SELECT [...] FROM [...] WHERE username = "$_POST["user"]" AND password = "$_POST["pass"]";";`
Rad 41:
`elseif ($result->num_rows == 1){`
`while($row = $result->fetch_assoc()) {`
`$_SESSION["loginT"] = true;`
`$_SESSION["username"] = $_POST["user"]; `
`$_SESSION["password"] =$_POST["pass"]; `
`$_SESSION["userid"] =$row["userid"];`
`}}`
Kontrollerar alltså om det finns ett returnerat värde från databasen - så fall är finns användaren med det lösenordet. Istället för att hämta alla användare.

**Comment by Hugsim** [comment]
Då öppnar vi upp för SQL-injection, detta sättet gör att vi är säkra från det.
