### ISSUE TITLE
Lösning på de visuella buggarna?

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#25]
#16 Referens till det tidigare påpekade problemet med visningen av bilder.
Vid _'granskning av element'_ på bilderna har de en CSS-attribut, **Zoom: 8;**, sätts detta till 1 så visas bilderna i rätt storlek och format.

- [ ] Ändra Zoom-attributet för img-taggarna från 8 till 1.

**Comment by Hugsim** [comment]
Zoom finns där för att lösa ett annat problem, och det funkar i både Firefox och Chrome, så vi ser inte att det är ett problem.

**Comment by Chrimle** [comment]
Men att ändra i filen _**stylesheetLastImages.css**_ på image img skapar användarmöjlighet för Internet Explorer-användare också! **Rad 19**

**Comment by Hugsim** [comment]
Problemet uppstår utan zoom i IE också. Uppgradera till en modern webbläsare.
