### ISSUE TITLE
Redigt anmärkningsvärd bugg som nu hindrar huvudfunktionen för tjänsten!

### ISSUE THREAD

**Issue by Chrimle** [Hugsim/GitGud#26]
#22 Referens till radioknapparnas required. Vid tillägget av required-attributen, togs value-attributet bort och bilden kommer inte att läggas till i databasen, då variabeln "radio" inte är tilldelad något värde.

- [x] Lägg tillbaka value="" på private/public-radioknapparna.

**Comment by Hugsim** [comment]
Fixat genom 9b1f245d9eb8afad879ef46a66c290ed79b1a843
